<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=1200px, shrink-to-fit=yes">
    <meta name="description" content="Bitcoin Core RPC Docs - XXX">
    <meta name="author" content="">

    <title>XXX - Bitcoin Core RPC Docs</title>

    <!-- Bootstrap core CSS -->
    <link href="./bootstrap.min.css" rel="stylesheet">
  </head>
  <style>
  .card-body {
    font-size:80%;
    padding-top: 0.5em;
  }
  pre {
    word-break: break-word;
    white-space: pre-wrap;
  }
  </style>

  <body>


    <nav class="navbar  navbar-dark bg-dark ">
      <a class="navbar-brand" href="/">Bitcoin Core RPC docs</a>
    </nav>

    <main role="main" class="container-fluid" style="margin-top: 1pc;">

      <div class="row">
        <div class="col-8 col-lg-9 col-xl-10">
          <h1>XXX - Bitcoin RPC</h1>
          <pre>
